# UV Configuration for PEM Project
# This file contains UV-specific configuration for the PEM project
# Documentation: https://docs.astral.sh/uv/configuration/

# Basic UV settings
native-tls = true
no-cache = false
cache-dir = ".uv-cache"

# Build configuration
no-build-isolation = false
compile-bytecode = true

# Publishing configuration
publish-url = "https://upload.pypi.org/legacy/"

# Dependency resolution
resolution = "highest"
prerelease = "disallow"

# Index configuration
index-url = "https://pypi.org/simple/"
